global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'service', 'env', 'team']
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 3h
  receiver: warning-stdout
  routes:
    - matchers:
        - alertname="Watchdog"
      receiver: watchdog-stdout
      repeat_interval: 5m
    - matchers:
        - severity="critical"
      receiver: critical-stdout
      group_wait: 10s
      group_interval: 3m
      repeat_interval: 30m
    - matchers:
        - severity="warning"
      receiver: warning-stdout
      group_wait: 1m
      group_interval: 15m
      repeat_interval: 6h

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ['alertname', 'service', 'env']

  - source_matchers:
      - alertname="ServiceAvailabilityProductionCritical"
    target_matchers:
      - alertname="PrometheusTargetDown"
      - env="production"
    equal: ['service', 'env']

receivers:
  - name: warning-stdout
    webhook_configs:
      - url: http://127.0.0.1:5001/warning
        send_resolved: true

  - name: critical-stdout
    webhook_configs:
      - url: http://127.0.0.1:5001/critical
        send_resolved: true

  - name: watchdog-stdout
    webhook_configs:
      - url: http://127.0.0.1:5001/watchdog
        send_resolved: true
